"""anymissedmigration

Revision ID: 8eefef142f0a
Revises: 8f97c03ec811
Create Date: 2023-12-05 13:51:48.278211

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "8eefef142f0a"
down_revision: Union[str, None] = "8f97c03ec811"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
